{
  imports = [
    ./desktop.nix
    ./xdg-mimeapps.nix
    ./appearance.nix
    ./kitty.nix
    ./shell.nix
    ./hyprland.nix
    ./hypridle.nix
    ./hyprsunset.nix
    ./screen-share.nix
    ./screenshot.nix
    ./voxtype.nix
    ./btop.nix
    ./nvim.nix
    ./git.nix
    ./ssh.nix
    ./web-apps.nix
    ./fzf.nix
    ./yazi.nix
    ./npm.nix
    ./quickshell.nix
    ./vscode.nix
    ./onepassword.nix
  ];
}
