pragma Singleton

// Immutable theme data generated by modules/home/quickshell.nix and loaded at startup.
import QtQuick
import Quickshell
import Quickshell.Io

Item {
    id: root

    property color base00: "#1a1b26"
    property color base01: "#13141c"
    property color base02: "#292e42"
    property color base03: "#414868"
    property color base04: "#565f89"
    property color base05: "#a9b1d6"
    property color base08: "#f7768e"

    // Text hierarchy always derives from the foreground instead of theme gray slots.
    readonly property color textPrimary: base05
    readonly property color textSecondary: Qt.rgba(base05.r, base05.g, base05.b, 0.65)
    readonly property color textMuted: Qt.rgba(base05.r, base05.g, base05.b, 0.4)

    // per-theme accent slot (themes/*/accent)
    property color accent: "#7aa2f7"
    property url wallpaper: ""
    property string monospace: "monospace"
    property int fontSize: 13

    function apply(data: var): void {
        base00 = data.base00;
        base01 = data.base01;
        base02 = data.base02;
        base03 = data.base03;
        base04 = data.base04;
        base05 = data.base05;
        base08 = data.base08;
        accent = data.accent;
        wallpaper = "file://" + data.wallpaper;
        monospace = data.monospace;
    }

    FileView {
        path: `${Quickshell.env("HOME")}/.config/quickshell-theme.json`
        preload: true
        printErrors: false
        onLoaded: root.apply(JSON.parse(text()))
    }
}
